-- MySQL Script generated by MySQL Workbench
-- Thu Jun 19 17:45:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DBclothing
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBclothing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBclothing` DEFAULT CHARACTER SET utf8 ;
USE `DBclothing` ;

-- -----------------------------------------------------
-- Table `DBclothing`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Branch` (
  `branch_code` VARCHAR(11) NOT NULL,
  `branch_name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `contact_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`branch_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `size` VARCHAR(10) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `quantity_in_stock` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `discontinued` BOOLEAN NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Customer` (
  `customer_id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isMember` BOOLEAN NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Sales Rep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Sales Rep` (
  `sales_rep_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `branch_code` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `hire_date` DATE NOT NULL,
  `active_status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`sales_rep_id`),
  INDEX `fk_Sales Rep_Branch1_idx` (`branch_code` ASC) VISIBLE,
  CONSTRAINT `fk_Sales Rep_Branch1`
    FOREIGN KEY (`branch_code`)
    REFERENCES `DBclothing`.`Branch` (`branch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Sales` (
  `sales_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `sales_rep_id` INT NOT NULL,
  `branch_code` VARCHAR(11) NOT NULL,
  `sale_date` DATE NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `total_amout` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sales_id`),
  INDEX `fk_Sales_Member1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_Sales_Sales Rep1_idx` (`sales_rep_id` ASC) VISIBLE,
  INDEX `fk_Sales_Branch1_idx` (`branch_code` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Member1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `DBclothing`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_Sales Rep1`
    FOREIGN KEY (`sales_rep_id`)
    REFERENCES `DBclothing`.`Sales Rep` (`sales_rep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_Branch1`
    FOREIGN KEY (`branch_code`)
    REFERENCES `DBclothing`.`Branch` (`branch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Sales Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Sales Items` (
  `sale_item_id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity_ordered` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`sale_item_id`),
  INDEX `fk_Sales Items_Sales1_idx` (`sale_id` ASC) VISIBLE,
  INDEX `fk_Sales Items_Product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales Items_Sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `DBclothing`.`Sales` (`sales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales Items_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `DBclothing`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Restock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Restock` (
  `restock_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `quantity_added` INT NOT NULL,
  `cost_price` DECIMAL(10,2) NOT NULL,
  `restock_date` DATE NOT NULL,
  PRIMARY KEY (`restock_id`),
  INDEX `fk_Restock_Product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Restock_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `DBclothing`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Returns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Returns` (
  `return_id` INT NOT NULL,
  `sale_id` INT NOT NULL,
  `return_date` DATE NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`return_id`),
  INDEX `fk_Returns_Sales1_idx` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `fk_Returns_Sales1`
    FOREIGN KEY (`sale_id`)
    REFERENCES `DBclothing`.`Sales` (`sales_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Return Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Return Items` (
  `return_item_id` INT NOT NULL,
  `return_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity_returned` INT NOT NULL,
  PRIMARY KEY (`return_item_id`),
  INDEX `fk_Return Items_Product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Return Items_Returns1_idx` (`return_id` ASC) VISIBLE,
  CONSTRAINT `fk_Return Items_Product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `DBclothing`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Return Items_Returns1`
    FOREIGN KEY (`return_id`)
    REFERENCES `DBclothing`.`Returns` (`return_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Stock Transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Stock Transfer` (
  `transfer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `source_branch_code` VARCHAR(11) NOT NULL,
  `dest_branch_code` VARCHAR(11) NOT NULL,
  `quantity_transferred` INT NOT NULL,
  `transfer_date` DATE NOT NULL,
  `reason` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`transfer_id`),
  INDEX `fk_Stock Transfer_Branch1_idx` (`source_branch_code` ASC) VISIBLE,
  INDEX `fk_Stock Transfer_Product2_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_Stock Transfer_Branch2_idx` (`dest_branch_code` ASC) VISIBLE,
  CONSTRAINT `fk_Stock Transfer_Branch1`
    FOREIGN KEY (`source_branch_code`)
    REFERENCES `DBclothing`.`Branch` (`branch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock Transfer_Product2`
    FOREIGN KEY (`product_id`)
    REFERENCES `DBclothing`.`Product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock Transfer_Branch2`
    FOREIGN KEY (`dest_branch_code`)
    REFERENCES `DBclothing`.`Branch` (`branch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBclothing`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBclothing`.`Member` (
  `member_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  `date_registered` DATE NOT NULL,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Member_Customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `DBclothing`.`Customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
